name: MLflow CI Training

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
    - name: set up job
      run: echo "Job setup start"

    - name: run actions/checkout@v3
      uses: actions/checkout@v3

    - name: set up python 3.12.7
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: 3.12.7
        environment-file: MLProject/conda.yaml
        activate-environment: mlflow-env

    - name: check env
      shell: bash -l {0}
      run: |
        python --version
        pip --version
        conda info
        conda list

    - name: install dependencies
      shell: bash -l {0}
      run: |
        pip install --upgrade pip
        pip install mlflow==2.19.0

    - name: set MLflow Tracking URL
      shell: bash -l {0}
      run: |
        export MLFLOW_TRACKING_URI=file://${{ github.workspace }}/MLProject/mlruns
        echo "MLFLOW_TRACKING_URI set to $MLFLOW_TRACKING_URI"

    - name: Run mlflow project
      working-directory: MLProject
      shell: bash -l {0}
      run: |
        conda activate mlflow-env
        mlflow run . --env-manager=local

    - name: install python dependencies
      shell: bash -l {0}
      run: conda list

    - name: upload to github
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-artifacts
        path: MLProject/mlruns

    - name: post set up python 3.12.7
      run: echo "Post setup Python complete"

    - name: post run actions/checkout@v3
      run: echo "Post checkout complete"

    - name: complete job
      run: echo "MLflow CI Training Completed"
